import "dotenv/config";
import { PrismaClient, DealStatus } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ----------------------------------------------------------------
// 拠点マスタ（14拠点）
// ----------------------------------------------------------------
const BRANCHES = [
  { id: "branch_hq", name: "本部", code: "HQ" },
  { id: "branch_isk", name: "石川", code: "ISK" },
  { id: "branch_kgo", name: "香川・岡山", code: "KGO" },
  { id: "branch_kyt", name: "京都", code: "KYT" },
  { id: "branch_tky", name: "東京（片桐）", code: "TKY" },
  { id: "branch_ymc", name: "山口・広島", code: "YMC" },
  { id: "branch_hkd", name: "北海道", code: "HKD" },
  { id: "branch_tk2", name: "東京（白石）", code: "TK2" },
  { id: "branch_kns", name: "関西（宮本）", code: "KNS" },
  { id: "branch_okn", name: "沖縄", code: "OKN" },
  { id: "branch_tks", name: "徳島", code: "TKS" },
  { id: "branch_ibk", name: "茨城", code: "IBK" },
  { id: "branch_fku", name: "福岡", code: "FKU" },
  { id: "branch_knw", name: "神奈川", code: "KNW" },
];

type CustomerRow = {
  id: string;
  name: string;
  phone: string | null;
  address: string | null;
  industry: string | null;
  branchId: string;
  isLocked: boolean;
  dealId: string;
  dealTitle: string;
  dealStatus: DealStatus;
  dealCloseDate: string;
};

// ----------------------------------------------------------------
// 顧客データ（76件）
// ----------------------------------------------------------------
const CUSTOMERS: CustomerRow[] = [
  {
    id: "cust_82",
    name: "オステリア ロンド",
    phone: "086-237-3627",
    address: "香川県岡山県岡山市北区柳町1-7-9矢吹ビル１F",
    industry: "飲食・宿泊・レジャー",
    branchId: "branch_kgo",
    isLocked: true,
    dealId: "deal_82_1",
    dealTitle: "集客・SNS運用支援提案",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-03-15",
  },
  {
    id: "cust_81",
    name: "京都日産自動車株式会社",
    phone: null,
    address: "京都府",
    industry: "商社・卸売",
    branchId: "branch_kyt",
    isLocked: false,
    dealId: "deal_81_1",
    dealTitle: "業界向けブランディング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-05-15",
  },
  {
    id: "cust_80",
    name: "NECグリーンロケッツ東葛",
    phone: null,
    address: "千葉県",
    industry: "エンタメ・レジャー",
    branchId: "branch_tky",
    isLocked: false,
    dealId: "deal_80_1",
    dealTitle: "イベント集客デジタル広告",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-04-15",
  },
  {
    id: "cust_79",
    name: "石川県警察本部 生活安全部 生活安全企画課",
    phone: null,
    address: "石川県",
    industry: "官公庁・自治体",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_79_1",
    dealTitle: "広報・情報発信デジタル支援",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-03-28",
  },
  {
    id: "cust_78",
    name: "株式会社ロピア",
    phone: null,
    address: "神奈川県",
    industry: "小売・EC",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_78_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-03-28",
  },
  {
    id: "cust_77",
    name: "朝日エイテック株式会社",
    phone: null,
    address: "石川県",
    industry: "建設・設備・工事業",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_77_1",
    dealTitle: "採用・ブランディング施策",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-03-15",
  },
  {
    id: "cust_76",
    name: "株式会社金沢すっぽん堂本舗",
    phone: null,
    address: "石川県",
    industry: "小売・EC",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_76_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-03-15",
  },
  {
    id: "cust_75",
    name: "北陸綜合警備保障株式会社",
    phone: null,
    address: "石川県",
    industry: "その他",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_75_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-04-28",
  },
  {
    id: "cust_74",
    name: "株式会社田中組",
    phone: null,
    address: null,
    industry: "建設・設備・工事業",
    branchId: "branch_hkd",
    isLocked: false,
    dealId: "deal_74_1",
    dealTitle: "株式会社田中組 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-02-01",
  },
  {
    id: "cust_73",
    name: "とんでん",
    phone: null,
    address: "北海道",
    industry: "飲食・宿泊・レジャー",
    branchId: "branch_hkd",
    isLocked: false,
    dealId: "deal_73_1",
    dealTitle: "集客・SNS運用支援提案",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-04-28",
  },
  {
    id: "cust_72",
    name: "アスクゲートイースト",
    phone: null,
    address: "北海道",
    industry: "人材・アウトソーシング",
    branchId: "branch_hkd",
    isLocked: false,
    dealId: "deal_72_1",
    dealTitle: "採用広告・求人支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-15",
  },
  {
    id: "cust_71",
    name: "エフ・プロジェクト株式会社",
    phone: null,
    address: "東京都",
    industry: "その他",
    branchId: "branch_tk2",
    isLocked: false,
    dealId: "deal_71_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_70",
    name: "株式会社ザ・ファースト",
    phone: null,
    address: "東京都",
    industry: "その他",
    branchId: "branch_tk2",
    isLocked: false,
    dealId: "deal_70_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-05-15",
  },
  {
    id: "cust_69",
    name: "ROHAKU建築設計",
    phone: null,
    address: "京都府",
    industry: "不動産・住宅",
    branchId: "branch_kyt",
    isLocked: false,
    dealId: "deal_69_1",
    dealTitle: "物件集客デジタル広告",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-04-28",
  },
  {
    id: "cust_68",
    name: "株式会社アイ・オー・データ機器",
    phone: null,
    address: "石川県",
    industry: "製造（機械・電気・電子）",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_68_1",
    dealTitle: "BtoB販促コンテンツ制作",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-05-20",
  },
  {
    id: "cust_67",
    name: "石川日産自動車販売株式会社",
    phone: null,
    address: "石川県",
    industry: "小売・EC",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_67_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROPOSAL" as DealStatus,
    dealCloseDate: "2026-04-20",
  },
  {
    id: "cust_66",
    name: "株式会社アクシス 岡山支社",
    phone: "0868050070",
    address: "岡山県岡山県岡山市北区下中野３６５番地１０３",
    industry: "広告・出版・マスコミ",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_66_1",
    dealTitle: "株式会社アクシス 岡山支社 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-03",
  },
  {
    id: "cust_65",
    name: "北陸スバル自動車株式会社",
    phone: null,
    address: "石川県",
    industry: "小売・EC",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_65_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-15",
  },
  {
    id: "cust_64",
    name: "株式会社エッジ・インターナショナル",
    phone: "03-3403-7750",
    address: "東京都東京都港区赤坂7-1-1青山安田ビル",
    industry: "コンサルティング・専門サービス",
    branchId: "branch_kns",
    isLocked: false,
    dealId: "deal_64_1",
    dealTitle: "コンテンツマーケティング支援",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-05-28",
  },
  {
    id: "cust_63",
    name: "社団法人石川県物産協会",
    phone: null,
    address: "石川県",
    industry: "団体・NPO・組合",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_63_1",
    dealTitle: "社団法人石川県物産協会 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-26",
  },
  {
    id: "cust_62",
    name: "株式会社アデランス",
    phone: null,
    address: "東京都",
    industry: "小売・EC",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_62_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-03-28",
  },
  {
    id: "cust_61",
    name: "三谷産業株式会社",
    phone: null,
    address: "石川県",
    industry: "建設・設備・工事業",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_61_1",
    dealTitle: "採用・ブランディング施策",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_60",
    name: "石川県漁業協同組合",
    phone: null,
    address: "石川県",
    industry: "団体・NPO・組合",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_60_1",
    dealTitle: "認知度向上・会員獲得支援",
    dealStatus: "PROPOSAL" as DealStatus,
    dealCloseDate: "2026-06-15",
  },
  {
    id: "cust_59",
    name: "金沢都市政策局　地域力再生化",
    phone: null,
    address: "石川県",
    industry: "官公庁・自治体",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_59_1",
    dealTitle: "広報・情報発信デジタル支援",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-05-28",
  },
  {
    id: "cust_58",
    name: "社会福祉法人りじょう福祉会",
    phone: "082-879-0479",
    address: "広島県広島市安佐南区大町東３丁目１２?３０",
    industry: "教育・学校・学習支援",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_58_1",
    dealTitle: "社会福祉法人りじょう福祉会 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-23",
  },
  {
    id: "cust_57",
    name: "学校法人鯉城学園",
    phone: "082-879-0479",
    address: "広島県広島市安佐南区大町東３丁目１２?３０",
    industry: "教育・学校・学習支援",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_57_1",
    dealTitle: "学校法人鯉城学園 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-02",
  },
  {
    id: "cust_56",
    name: "一般財団法人やない花のまちづくり振興財団",
    phone: "0820-24-1187",
    address: "山口県山口県柳井市新庄500-1",
    industry: "エンタメ・レジャー",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_56_1",
    dealTitle: "イベント集客デジタル広告",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-04-20",
  },
  {
    id: "cust_55",
    name: "農林水産省 北陸農政局",
    phone: null,
    address: "石川県石川県金沢市広坂２丁目２－６０",
    industry: "官公庁・自治体",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_55_1",
    dealTitle: "農林水産省 北陸農政局 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-28",
  },
  {
    id: "cust_54",
    name: "株式会社Various",
    phone: null,
    address: "東京都",
    industry: "コンサルティング・専門サービス",
    branchId: "branch_tky",
    isLocked: false,
    dealId: "deal_54_1",
    dealTitle: "株式会社Various 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-28",
  },
  {
    id: "cust_53",
    name: "税理士法人原田税務会計事務所",
    phone: "03-3583-7737",
    address: "東京都",
    industry: "コンサルティング・専門サービス",
    branchId: "branch_tky",
    isLocked: false,
    dealId: "deal_53_1",
    dealTitle: "税理士法人原田税務会計事務所 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-13",
  },
  {
    id: "cust_52",
    name: "株式会社福岡商会",
    phone: null,
    address: "石川県",
    industry: "製造（食品・飲料・化粧品）",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_52_1",
    dealTitle: "食品ブランド販促支援",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_51",
    name: "西山産業開発株式会社",
    phone: null,
    address: "石川県",
    industry: "建設・設備・工事業",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_51_1",
    dealTitle: "採用・ブランディング施策",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-05-15",
  },
  {
    id: "cust_50",
    name: "会宝産業株式会社",
    phone: null,
    address: "石川県",
    industry: "商社・卸売",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_50_1",
    dealTitle: "業界向けブランディング支援",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-05-20",
  },
  {
    id: "cust_49",
    name: "一般社団法人石川県物産協会",
    phone: null,
    address: "石川県",
    industry: "その他",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_49_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "PROPOSAL" as DealStatus,
    dealCloseDate: "2026-05-28",
  },
  {
    id: "cust_48",
    name: "株式会社アンガット",
    phone: "0989417200",
    address: "沖縄県沖縄県那覇市おもろまち2丁目6-11フロンティアビル (南3F)",
    industry: "小売・EC",
    branchId: "branch_okn",
    isLocked: false,
    dealId: "deal_48_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-03-28",
  },
  {
    id: "cust_47",
    name: "六花亭",
    phone: null,
    address: "北海道",
    industry: "製造（食品・飲料・化粧品）",
    branchId: "branch_hkd",
    isLocked: false,
    dealId: "deal_47_1",
    dealTitle: "六花亭 過去案件",
    dealStatus: "CLOSED_LOST" as DealStatus,
    dealCloseDate: "2025-11-18",
  },
  {
    id: "cust_46",
    name: "徳島ヴォルティス株式会社",
    phone: "088-672-7252",
    address: "徳島県徳島県板野郡板野町犬伏字瓢谷2-22",
    industry: "その他",
    branchId: "branch_tks",
    isLocked: false,
    dealId: "deal_46_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "QUALIFYING" as DealStatus,
    dealCloseDate: "2026-04-15",
  },
  {
    id: "cust_44",
    name: "四国計測工業株式会社",
    phone: "0877-33-2221",
    address: "香川県香川県仲多度郡多度津町南鴨200番地1",
    industry: "製造（機械・電気・電子）",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_44_1",
    dealTitle: "BtoB販促コンテンツ制作",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-06-20",
  },
  {
    id: "cust_43",
    name: "株式会社アーバンレック",
    phone: "087-822-0210",
    address: "香川県香川県高松市磨屋町6番地6",
    industry: "不動産・住宅",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_43_1",
    dealTitle: "株式会社アーバンレック 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-02-08",
  },
  {
    id: "cust_42",
    name: "株式会社道とん堀",
    phone: "042-551-5041",
    address: "東京都東京都福生市加美平一丁目6番地17",
    industry: "飲食・宿泊・レジャー",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_42_1",
    dealTitle: "集客・SNS運用支援提案",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-03-15",
  },
  {
    id: "cust_41",
    name: "有限会社筑波ハム",
    phone: "029-879-9101",
    address: "茨城県茨城県つくば市下平塚３５６番地の１",
    industry: "製造（食品・飲料・化粧品）",
    branchId: "branch_ibk",
    isLocked: false,
    dealId: "deal_41_1",
    dealTitle: "有限会社筑波ハム 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-26",
  },
  {
    id: "cust_40",
    name: "NPO法人ＴＯＰ　ＦＩＧＨＴＥＲ　ＪＡＰＡＮ",
    phone: null,
    address: "茨城県茨城県稲敷郡阿見町大字青宿字古山台６７６番１４",
    industry: "団体・NPO・組合",
    branchId: "branch_ibk",
    isLocked: false,
    dealId: "deal_40_1",
    dealTitle: "NPO法人ＴＯＰ　ＦＩＧＨＴＥＲ　ＪＡＰＡＮ 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-13",
  },
  {
    id: "cust_39",
    name: "Beauty Japan 茨城大会運営事務局",
    phone: null,
    address: "茨城県茨城県守谷市中2-17-1",
    industry: "団体・NPO・組合",
    branchId: "branch_ibk",
    isLocked: false,
    dealId: "deal_39_1",
    dealTitle: "Beauty Japan 茨城大会運営事務局 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-03",
  },
  {
    id: "cust_38",
    name: "有限会社猪瀬電気",
    phone: "0297-68-9429",
    address: "茨城県茨城県北相馬郡利根町もえぎ野台1-1-1",
    industry: "建設・設備・工事業",
    branchId: "branch_ibk",
    isLocked: false,
    dealId: "deal_38_1",
    dealTitle: "有限会社猪瀬電気 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-19",
  },
  {
    id: "cust_37",
    name: "ANDSUNS株式会社",
    phone: null,
    address: "茨城県茨城県下妻市平方１９４",
    industry: "建設・設備・工事業",
    branchId: "branch_ibk",
    isLocked: false,
    dealId: "deal_37_1",
    dealTitle: "ANDSUNS株式会社 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-07",
  },
  {
    id: "cust_36",
    name: "株式会社UNICO",
    phone: "0297-44-6123",
    address: "茨城県茨城県守谷市緑2-25-10",
    industry: "製造（機械・電気・電子）",
    branchId: "branch_ibk",
    isLocked: false,
    dealId: "deal_36_1",
    dealTitle: "株式会社UNICO 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-01-13",
  },
  {
    id: "cust_35",
    name: "株式会社さとう",
    phone: null,
    address: "京都府",
    industry: "小売・EC",
    branchId: "branch_kyt",
    isLocked: false,
    dealId: "deal_35_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-15",
  },
  {
    id: "cust_34",
    name: "タニコー株式会社 高松営業所",
    phone: "087-813-3170",
    address: "香川県香川県高松市常磐町1-3-1瓦町フラッグ地下１F",
    industry: "製造（機械・電気・電子）",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_34_1",
    dealTitle: "BtoB販促コンテンツ制作",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-05-15",
  },
  {
    id: "cust_33",
    name: "JR西日本京都SC開発株式会社",
    phone: "075-365-7514",
    address: "京都府京都府京都市下京区東塩小路町579-27木津屋橋ビル",
    industry: "その他",
    branchId: "branch_kns",
    isLocked: false,
    dealId: "deal_33_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-04-28",
  },
  {
    id: "cust_32",
    name: "アクアクララ京都株式会社",
    phone: "075-631-7860",
    address: "京都府京都府久世郡久御山町野村村東182",
    industry: "小売・EC",
    branchId: "branch_kns",
    isLocked: false,
    dealId: "deal_32_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-05-28",
  },
  {
    id: "cust_31",
    name: "株式会社岡山乗馬倶楽部",
    phone: "0867-34-9911",
    address: "岡山県岡山県加賀郡吉備中央町上田西2393-11",
    industry: "エンタメ・レジャー",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_31_1",
    dealTitle: "イベント集客デジタル広告",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_30",
    name: "西日本放送株式会社",
    phone: "087-826-7333",
    address: "香川県香川県高松市丸の内8番15号",
    industry: "広告・出版・マスコミ",
    branchId: "branch_kgo",
    isLocked: true,
    dealId: "deal_30_1",
    dealTitle: "西日本放送株式会社 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-01-12",
  },
  {
    id: "cust_29",
    name: "アマゾンジャパン",
    phone: null,
    address: "東京都",
    industry: "小売・EC",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_29_1",
    dealTitle: "アマゾンジャパン 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-05",
  },
  {
    id: "cust_28",
    name: "株式会社SaraBe",
    phone: null,
    address: "徳島県徳島県徳島市国府町和田字表２０番地７",
    industry: "その他",
    branchId: "branch_tks",
    isLocked: false,
    dealId: "deal_28_1",
    dealTitle: "株式会社SaraBe 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-02-16",
  },
  {
    id: "cust_27",
    name: "ECC_犬伏由美",
    phone: "https://ecc-aizumi.com/lp/2026-early-start/",
    address: "徳島県",
    industry: "教育・学校・学習支援",
    branchId: "branch_tks",
    isLocked: false,
    dealId: "deal_27_1",
    dealTitle: "ECC_犬伏由美 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-25",
  },
  {
    id: "cust_26",
    name: "株式会社テレビ東京",
    phone: null,
    address: "東京都東京都港区六本木3-2-1 六本木グランドタワー",
    industry: "広告・出版・マスコミ",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_26_1",
    dealTitle: "株式会社テレビ東京 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-28",
  },
  {
    id: "cust_25",
    name: "スポーツコミュニケーションKYOTO株式会社",
    phone: null,
    address: "京都府",
    industry: "その他",
    branchId: "branch_kyt",
    isLocked: false,
    dealId: "deal_25_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-03-15",
  },
  {
    id: "cust_24",
    name: "イオンエンターテイメント株式会社",
    phone: null,
    address: "東京都",
    industry: "エンタメ・レジャー",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_24_1",
    dealTitle: "イオンエンターテイメント株式会社 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-26",
  },
  {
    id: "cust_21",
    name: "安藤工事株式会社",
    phone: "092-561-7012",
    address: "福岡県福岡県福岡市南区清水2丁目9番6号",
    industry: "建設・設備・工事業",
    branchId: "branch_fku",
    isLocked: false,
    dealId: "deal_21_1",
    dealTitle: "採用・ブランディング施策",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_20",
    name: "株式会社すかいらーくホールディングス",
    phone: null,
    address: "東京都",
    industry: "飲食・宿泊・レジャー",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_20_1",
    dealTitle: "株式会社すかいらーくホールディングス 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-13",
  },
  {
    id: "cust_19",
    name: "株式会社京都パープルサンガ",
    phone: null,
    address: "京都府",
    industry: "その他",
    branchId: "branch_kyt",
    isLocked: false,
    dealId: "deal_19_1",
    dealTitle: "マーケティング総合支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_18",
    name: "三井アウトレットパーク横浜ベイサイド",
    phone: null,
    address: "神奈川県",
    industry: "小売・EC",
    branchId: "branch_knw",
    isLocked: false,
    dealId: "deal_18_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-06-28",
  },
  {
    id: "cust_17",
    name: "ラゾーナ川崎プラザ",
    phone: null,
    address: "神奈川県",
    industry: "小売・EC",
    branchId: "branch_knw",
    isLocked: false,
    dealId: "deal_17_1",
    dealTitle: "ECデジタルマーケティング支援",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-05-28",
  },
  {
    id: "cust_16",
    name: "株式会社BigNext",
    phone: "09024305422",
    address: "神奈川県神奈川県横浜市港北区鳥山町1266-1",
    industry: "商社・卸売",
    branchId: "branch_knw",
    isLocked: false,
    dealId: "deal_16_1",
    dealTitle: "株式会社BigNext 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-22",
  },
  {
    id: "cust_15",
    name: "横浜ビーコルセアーズ",
    phone: null,
    address: "神奈川県",
    industry: "エンタメ・レジャー",
    branchId: "branch_knw",
    isLocked: false,
    dealId: "deal_15_1",
    dealTitle: "イベント集客デジタル広告",
    dealStatus: "PROSPECTING" as DealStatus,
    dealCloseDate: "2026-03-28",
  },
  {
    id: "cust_14",
    name: "学校法人三幸学園 沖縄みらいAI&IT専門学校",
    phone: "050-5805-3567",
    address: "沖縄県沖縄県那覇市泊2?6?8",
    industry: "教育・学校・学習支援",
    branchId: "branch_okn",
    isLocked: false,
    dealId: "deal_14_1",
    dealTitle: "学校法人三幸学園 沖縄みらいAI&IT専門学校 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-02-25",
  },
  {
    id: "cust_13",
    name: "銭形ロックフェス実行委員会",
    phone: null,
    address: "香川県香川県観音寺市",
    industry: "エンタメ・レジャー",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_13_1",
    dealTitle: "イベント集客デジタル広告",
    dealStatus: "NEGOTIATION" as DealStatus,
    dealCloseDate: "2026-05-15",
  },
  {
    id: "cust_12",
    name: "香川日産自動車株式会社",
    phone: "087-831-1451",
    address: "香川県高松市花園町1丁目1番8号",
    industry: "小売・EC",
    branchId: "branch_kgo",
    isLocked: false,
    dealId: "deal_12_1",
    dealTitle: "香川日産自動車株式会社 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-14",
  },
  {
    id: "cust_11",
    name: "株式会社Plan・Do・See",
    phone: null,
    address: "京都府",
    industry: "飲食・宿泊・レジャー",
    branchId: "branch_kyt",
    isLocked: false,
    dealId: "deal_11_1",
    dealTitle: "株式会社Plan・Do・See 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-15",
  },
  {
    id: "cust_10",
    name: "株式会社ウッドワン",
    phone: null,
    address: "広島県広島県廿日市市木材港南1-1",
    industry: "製造（その他）",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_10_1",
    dealTitle: "株式会社ウッドワン 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-24",
  },
  {
    id: "cust_9",
    name: "青藍会グループ",
    phone: "083-933-6000",
    address: "山口県山口市吉敷中東1丁目1-1",
    industry: "医療・介護・福祉",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_9_1",
    dealTitle: "青藍会グループ 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-17",
  },
  {
    id: "cust_8",
    name: "株式会社山口井筒屋",
    phone: "083-902-1111",
    address: "山口県山口県山口市中市町３?３",
    industry: "小売・EC",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_8_1",
    dealTitle: "株式会社山口井筒屋 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-11-17",
  },
  {
    id: "cust_7",
    name: "株式会社レノファ山口",
    phone: "083-941-6792",
    address: "山口県山口県山口市赤妻町3-5",
    industry: "その他",
    branchId: "branch_ymc",
    isLocked: false,
    dealId: "deal_7_1",
    dealTitle: "株式会社レノファ山口 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-10-28",
  },
  {
    id: "cust_6",
    name: "金沢市市民局",
    phone: null,
    address: "石川県",
    industry: "官公庁・自治体",
    branchId: "branch_isk",
    isLocked: false,
    dealId: "deal_6_1",
    dealTitle: "金沢市市民局 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2025-12-27",
  },
  {
    id: "cust_5",
    name: "ビジネスエンジニアリング株式会社",
    phone: "03-3510-1590",
    address: "東京都東京都千代田区大手町1-8-1KDDI大手町ビル",
    industry: "IT・Web・通信",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_5_1",
    dealTitle: "ビジネスエンジニアリング株式会社 継続サポート",
    dealStatus: "CLOSED_WON" as DealStatus,
    dealCloseDate: "2026-02-20",
  },
  {
    id: "cust_2",
    name: "株式会社バンダイナムコネットワークサービス",
    phone: "03-6744-4115",
    address: "東京都港区芝五丁目37-8バンダイナムコ来研究所",
    industry: "エンタメ・レジャー",
    branchId: "branch_hq",
    isLocked: false,
    dealId: "deal_2_1",
    dealTitle: "イベント集客デジタル広告",
    dealStatus: "PROPOSAL" as DealStatus,
    dealCloseDate: "2026-04-20",
  },
];

// ----------------------------------------------------------------
// シード実行
// ----------------------------------------------------------------
async function main() {
  console.log("🌱 Seeding database...");

  // 既存データを削除（外部キー制約の順番に注意）
  await prisma.deal.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.branch.deleteMany();
  console.log("🗑️  Cleared existing data");

  // 拠点を作成
  for (const b of BRANCHES) {
    await prisma.branch.create({ data: b });
  }
  console.log(`✅ Created ${BRANCHES.length} branches`);

  // 顧客 + 商談を作成
  const lockExpiry = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000); // 3日後
  let count = 0;
  for (const c of CUSTOMERS) {
    await prisma.customer.create({
      data: {
        id: c.id,
        name: c.name,
        phone: c.phone,
        address: c.address,
        industry: c.industry,
        branchId: c.branchId,
        lockExpiresAt: c.isLocked ? lockExpiry : null,
        lockedAt: c.isLocked ? new Date() : null,
        deals: {
          create: {
            id: c.dealId,
            title: c.dealTitle,
            status: c.dealStatus,
            amount: null,
            branchId: c.branchId,
            expectedCloseDate: new Date(c.dealCloseDate),
          },
        },
      },
    });
    count++;
  }
  console.log(`✅ Created ${count} customers with deals`);
  console.log("🎉 Seeding complete!");
}

main()
  .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
