"use client";
/* eslint-disable @next/next/no-img-element -- Authenticated photo previews must keep the browser session cookie. */
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import type { JournalContent } from "@/lib/journal/model";
import JournalEditor, { type EditableEntry, type AuthorDefaults } from "./editor";
import styles from "./desk.module.css";
type Row={id:string;ownerId?:string;title:string;externalId:string;revision:number;status:string;kind:string;slug:string;ownerName:string;updatedAt:string;approvedRevision:number|null;deliveredRevision:number|null;reviewNote:string|null;firstPublishedAt?:string|null;content?:JournalContent};
const status:Record<string,string>={DRAFT:"下書き",IN_REVIEW:"確認待ち",APPROVED:"承認済み",ARCHIVED:"保管中"};
async function api(path:string,method="GET",data?:unknown){const r=await fetch(`/api/journal/${path}`,{method,headers:data instanceof FormData?{}:{"Content-Type":"application/json"},body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error??"処理に失敗しました");return v;}
export default function JournalDesk({admin,viewerId,defaults,photoUrl=(id:string)=>`/api/journal/photos/${id}`}:{admin:boolean;viewerId?:string;defaults?:AuthorDefaults;photoUrl?:(id:string)=>string}){
  const [editing,setEditing]=useState<EditableEntry|null>(null),[editorKey,setEditorKey]=useState(0),[editorVisible,setEditorVisible]=useState(!admin),[dirty,setDirty]=useState(false);
  const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<string[]>([]),[item,setItem]=useState<Row|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[sort,setSort]=useState("new"),[filter,setFilter]=useState(""),[input,setInput]=useState(""),[note,setNote]=useState(""),[facts,setFacts]=useState(false),[rights,setRights]=useState(false),[person,setPerson]=useState(false),[slugEdit,setSlugEdit]=useState("");
  const refresh=useCallback(async()=>setRows(await api("entries")),[]);
  useEffect(()=>{refresh().catch(e=>setMessage(e.message));},[refresh]);
  // 通知から開いたとき（?id=）は、その原稿を最初に表示する
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get("id");if(id)open(id).catch(e=>setMessage(e.message));},[]);
  async function act(fn:()=>Promise<void>){setBusy(true);setMessage("");try{await fn();await refresh();}catch(e){setMessage(e instanceof Error?e.message:"処理に失敗しました");}finally{setBusy(false);}}
  const visible=rows.filter(r=>(!filter||r.status===filter)&&`${r.title} ${r.ownerName}`.includes(query)&&(!from||new Date(r.updatedAt).toLocaleDateString("en-CA",{timeZone:"Asia/Tokyo"})>=from)&&(!to||new Date(r.updatedAt).toLocaleDateString("en-CA",{timeZone:"Asia/Tokyo"})<=to)).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title,"ja"):sort==="old"?a.updatedAt.localeCompare(b.updatedAt):b.updatedAt.localeCompare(a.updatedAt));
  async function open(id:string){const r=await api(`entries?id=${encodeURIComponent(id)}`);setItem(r);setSlugEdit(r.slug);setFacts(false);setRights(false);setPerson(false);setNote("");}
  function newArticle(){if(dirty&&!confirm("保存していない編集を破棄して、新しい記事を作りますか？"))return;setEditing(null);setEditorKey(k=>k+1);setDirty(false);setItem(null);setEditorVisible(true);setMessage("");}
  async function saved(id:string){const r=await api(`entries?id=${encodeURIComponent(id)}`);setEditing(r);setItem(r);setDirty(false);setEditorVisible(false);setMessage("下書きを保存しました。本文と写真を確認して、本部へ提出できます。");await refresh();}
  function editArticle(){if(!item?.content)return;if(dirty&&!confirm("保存していない編集を破棄して、この原稿を開きますか？"))return;setEditing({...item,content:item.content});setEditorKey(k=>k+1);setDirty(false);setEditorVisible(true);window.scrollTo({top:0,behavior:"smooth"});}
  return <main className={styles.desk}>
    <p className={styles.hint}>アドアーチ Journal</p><h1>{admin?"みんなの原稿を、読みものに。":"あなたの仕事を、まちへ届けよう。"}</h1>
    <p className={styles.lead}>写真と、あなたの言葉で。最終原稿を貼り付けても、この画面で書き進めても大丈夫です。<br/>{admin?"原稿と写真・出典を確認し、よければ公開待ちへ。同期が完了すると「公開反映済み」に変わります。":"写真・見出し・本文を整えて、内容を確認してから本部へ渡してください。"}</p>
    <div className={styles.tools}><Link className={styles.link} href="/dashboard/work/library">資料・事例を見る</Link>{admin&&<Link className={styles.link} href="/dashboard/journal">自分の記事をつくる</Link>}<button disabled={busy} onClick={()=>act(refresh)}>更新</button></div>
    <details><summary>AIに整理を頼むときの依頼文（任意）</summary><p className={styles.lead}>「アドアーチJournalに載せる記事を一緒に作って。OSのjournal_guideを読んで、私のメモと写真から身近な言葉で書いてください。足りない事実は質問して。原稿を私に見せてからjournal_save_draftで保存し、確認を依頼してください。」</p></details>
    {admin&&<details><summary>写真を追加する</summary><p className={styles.hint}>笑顔・仕事中・地元での1枚など。JPEG / PNG / WebP、8MB以内。</p><input aria-label="写真を選択" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(!f)return;void act(async()=>{const form=new FormData();form.set("photo",f);const p=await api("photos","POST",form);setMessage(`写真を登録しました。AIには「journal_photosで写真IDを確認して使って」と伝えてください。\n写真ID: ${p.assetId}`);});}}/></details>}
    {!admin&&<><div className={styles.tools}><button onClick={newArticle}>新しい記事を書く</button><button onClick={()=>setEditorVisible(v=>!v)}>{editorVisible?"自分の原稿を見る":"編集中の記事に戻る"}</button></div><div hidden={!editorVisible}><JournalEditor key={`${editing?.id??"new"}:${editing?.revision??0}:${editorKey}`} entry={editing} defaults={defaults} onSaved={saved} onDirty={()=>setDirty(true)} photoUrl={photoUrl}/></div></>}
    {!admin&&<details><summary>外部ツール連携用データを読み込む（JSON）</summary><p className={styles.hint}>OSとAIが直接つながらない場合、journal_guideの形式の投稿データを貼り付けられます。</p><textarea aria-label="外部ツール連携用の投稿データ" value={input} onChange={e=>setInput(e.target.value)}/><button disabled={busy||!input} onClick={()=>act(async()=>{const r=await api("entries","POST",JSON.parse(input));setInput("");await saved(r.id);})}>下書きに保存</button></details>}
    <div hidden={!admin&&editorVisible}>
    <div className={styles.tools}><label>記事を探す<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="タイトル・投稿者"/></label><label>状態<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべて</option>{Object.entries(status).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>更新日から<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>まで<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>並べ方<select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">新しい順</option><option value="old">古い順</option><option value="title">タイトル順</option></select></label></div>
    <div className={styles.tools}><button disabled={busy} onClick={()=>setSelected(selected.length?[]:visible.map(r=>r.id))}>{selected.length?"選択を解除":"表示中を選択"}</button><button disabled={busy||!selected.length} onClick={()=>{if(confirm("選んだ未公開の下書きを保管します。公開経験のある記事は変更しません。"))void act(async()=>{const r=await api("entries","DELETE",{ids:selected});setSelected([]);setItem(null);setMessage(`${r.count}件を保管しました。`);});}}>下書きを一括整理</button></div>
    <p className={styles.hint}>公開した記事は削除せず保管します。掲載終了は本部の「掲載を取り下げる」から行います。</p>
    {message&&<p role="status" className={styles.message}>{message}</p>}
    <div className={styles.table}><table><thead><tr><th>選択</th><th>記事</th><th>投稿者</th><th>状態</th><th>更新日</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><input type="checkbox" aria-label={`${r.title}を選択`} checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/></td><td><button onClick={()=>act(()=>open(r.id))}>{r.title}</button></td><td>{r.ownerName}</td><td className={styles.status}>{status[r.status]}<br/><small>{r.approvedRevision!==null?(r.deliveredRevision===r.approvedRevision?"公開反映済み":"公開反映待ち"):r.firstPublishedAt?(r.deliveredRevision===r.revision?"掲載終了":"取り下げ反映待ち"):""}</small></td><td>{new Date(r.updatedAt).toLocaleString("ja-JP")}</td></tr>)}</tbody></table>{!visible.length&&<p className={styles.empty}>原稿が届くと、ここに並びます。</p>}</div>
    {item?.content&&<section className={styles.detail}><p>{item.content.category} ／ {item.content.region} ／ {item.content.company}</p><h2>{item.title}</h2><p>{item.content.summary}</p>{item.content.occurredOn&&<p className={styles.hint}>実施時期 {item.content.occurredOn}</p>}<div className={styles.photos}>{item.content.photos.map(p=><figure key={p.assetId}><img src={photoUrl(p.assetId)} alt={p.alt}/><figcaption>{p.caption} ／ {p.credit}</figcaption></figure>)}</div>{item.content.blocks.map((b,i)=>b.type==="heading"?<h2 key={i}>{b.text}</h2>:b.type==="quote"?<blockquote key={i}>{b.text}</blockquote>:<p key={i}>{b.text}</p>)}<h2>確認のための資料</h2>{item.content.evidence.map((s,i)=><p key={i}>{s.label}：{s.reference}<br/>{s.note}</p>)}<p className={styles.hint}>この資料欄は一般公開されません。</p>{item.content.publicSources.map((s,i)=><p key={i}>公開出典：<a href={s.url} target="_blank" rel="noreferrer">{s.label}</a></p>)}{item.reviewNote&&<p className={styles.message}>{item.reviewNote}</p>}
    {!admin&&<div className={styles.tools}><button onClick={editArticle}>この原稿を編集</button></div>}
    {admin?<><label>公開URL（https://adarch.co.jp/journal/{item.kind==="person"?"people/":""}…/）<input value={slugEdit} disabled={!!item.firstPublishedAt} maxLength={80} pattern="[a-z0-9]+(-[a-z0-9]+)*" onChange={e=>setSlugEdit(e.target.value.toLowerCase())}/></label><p className={styles.hint}>{item.firstPublishedAt?"公開済みのためURL名は変更できません。":"半角小文字・数字・ハイフン。承認するとこのURL名で確定します。"}</p><div className={styles.checks}><label><input type="checkbox" checked={facts} onChange={e=>setFacts(e.target.checked)}/>事実・担当範囲・実施時期を確認しました</label><label><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>写真・社名・実績の掲載範囲を確認しました</label>{item.content.kind==="person"&&<label><input type="checkbox" checked={person} onChange={e=>setPerson(e.target.checked)}/>人物紹介・発言をご本人が確認しました</label>}</div><label>編集メモ<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className={styles.tools}>{(["approve","return","withdraw"] as const).map(action=><button key={action} className={action==="approve"?styles.primary:undefined} disabled={busy||(action!=="withdraw"&&item.status!=="IN_REVIEW"&&!(action==="approve"&&item.status==="DRAFT"&&!!viewerId&&item.ownerId===viewerId))} onClick={()=>{if(action==="withdraw"&&!confirm("この記事の掲載を取り下げますか？次の同期で公開ページが切り替わります。"))return;void act(async()=>{await api("review","POST",{id:item.id,revision:item.revision,action,factsChecked:facts,rightsChecked:rights,personChecked:person,note,...(action==="approve"&&slugEdit&&slugEdit!==item.slug?{slug:slugEdit}:{})});await open(item.id);setMessage(action==="approve"?"承認しました。5分ほどでJournalに載ります。":"状態を更新しました。");});}}>{action==="approve"?"この原稿で公開を承認":action==="return"?"修正をお願いする":"掲載を取り下げる"}</button>)}</div></>:<button className={styles.primary} disabled={busy||item.status!=="DRAFT"} onClick={()=>act(async()=>{await api("entries","PATCH",{id:item.id,revision:item.revision});await open(item.id);setMessage("本部の確認待ちになりました。");})}>内容を確認して、本部へ渡す</button>}</section>}
    </div>
  </main>;
}
